
name: iOS UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ui-tests:
    name: UI Tests (${{ matrix.environment }})
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        environment: [DEV, QA, STAGING]

    env:
      APP_ENV: ${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show available simulators
        run: xcrun simctl list devices available

      - name: Run Product Configuration Matrix UI Test
        run: |
          set -o pipefail
          xcodebuild test \
            -project AppleQATest.xcodeproj \
            -scheme AppleQATest \
            -testPlan AppleQATestTestPlan
            -sdk iOS Simulator \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro' \
            -only-testing:AppleQATestUITests/ProductConfigurationMatrixTests \
            -parallel-testing-enabled YES \
            | tee xcodebuild-${{ matrix.environment }}.log

      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log-${{ matrix.environment }}
          path: xcodebuild-${{ matrix.environment }}.log
